# Generated by Django 6.0.2 on 2026-02-28 11:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agent_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
