# Generated by Django 6.0.2 on 2026-02-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='poste',
            field=models.CharField(default='Non défini', max_length=100),
            preserve_default=False,
        ),
    ]
