# Generated by Django 6.0.3 on 2026-04-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_agent_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='structure_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('directeur', 'Directeur'), ('directeur_region', 'Directeur de Région'), ('responsable_structure', 'Responsable de Structure'), ('divisionnaire', 'Divisionnaire'), ('agent', 'Agent')], max_length=30),
        ),
    ]
