# Generated by Django 6.0.3 on 2026-03-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('perm', models.CharField(blank=True, max_length=10, null=True)),
                ('famille', models.CharField(blank=True, max_length=50, null=True)),
                ('code_division', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('cout_initial_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cout_initial_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('realisation_cumul_n_mins1_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('realisation_cumul_n_mins1_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('real_s1_n_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('real_s1_n_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_s2_n_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_s2_n_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_cloture_n_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_cloture_n_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus1_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus1_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reste_a_realiser_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reste_a_realiser_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus2_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus2_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus3_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus3_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus4_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus4_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus5_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prev_n_plus5_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('janvier_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('janvier_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fevrier_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fevrier_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mars_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mars_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('avril_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('avril_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mai_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mai_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('juin_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('juin_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('juillet_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('juillet_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aout_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aout_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('septembre_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('septembre_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('octobre_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('octobre_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('novembre_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('novembre_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('decembre_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('decembre_dont_dex', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='excel_recap.excelupload')),
            ],
        ),
    ]
