# Generated by Django 6.0.3 on 2026-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrecord',
            name='perm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
