# Generated by Django 6.0.3 on 2026-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0002_alter_budgetrecord_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
