# Generated by Django 6.0.3 on 2026-04-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0003_budgetrecord_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_chef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_directeur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_directeur_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_divisionnaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_rejet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_validation_chef',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_validation_directeur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_validation_directeur_region',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_validation_divisionnaire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='rejete_par',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide_directeur_region', 'Validé Directeur Région'), ('valide_chef', 'Validé Chef'), ('valide_directeur', 'Validé Directeur'), ('valide_divisionnaire', 'Validé Divisionnaire'), ('rejete', 'Rejeté')], default='brouillon', max_length=50),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='valide_par_chef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='valide_par_directeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='valide_par_directeur_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='valide_par_divisionnaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
